# Development values for mcp-proxy
# This file contains development-friendly settings

replicaCount: 1

image:
  repository: ghcr.io/your-username/mcp-proxy
  pullPolicy: Always
  tag: "main-latest"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 64Mi

service:
  type: NodePort
  port: 3000

ingress:
  enabled: false

persistence:
  enabled: false

autoscaling:
  enabled: false

env:
  - name: PORT
    value: "3000"
  - name: PROJECT_DIR
    value: "/config"
  - name: RUST_LOG
    value: "debug"
  - name: RUST_BACKTRACE
    value: "full"

config:
  servers:
    mcpServers:
      filesystem:
        command: "npx"
        args: ["-y", "@modelcontextprotocol/server-filesystem", "/tmp"]
        env: {}
        disabled: false
      fetch:
        command: "npx"
        args: ["-y", "@modelcontextprotocol/server-fetch"]
        env: {}
        disabled: false