apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-mcp-server.fullname" . }}
  labels:
    {{- include "k8s-mcp-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-mcp-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-mcp-server.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "k8s-mcp-server.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.env.SERVER_PORT }}
              protocol: TCP
          env:
            - name: SERVER_MODE
              value: {{ .Values.env.SERVER_MODE | quote }}
            - name: SERVER_PORT
              value: {{ .Values.env.SERVER_PORT | quote }}
          {{- if .Values.useKubeconfigSecret }}
            - name: KUBECONFIG
              value: "/home/appuser/.kube/config"
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.useKubeconfigSecret }}
          volumeMounts:
            - name: kubeconfig
              mountPath: /home/appuser/.kube
              readOnly: true
          {{- end }}
      {{- if .Values.useKubeconfigSecret }}
      volumes:
        - name: kubeconfig
          secret:
            secretName: {{ .Values.kubeconfigSecretName }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}