apiVersion: v2
name: k8s-mcp-server
description: Helm chart for deploying the Kubernetes MCP server
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: Your Team
    email: your@email.com
keywords:
  - kubernetes
  - mcp
  - server
home: https://your-project-repo
sources:
  - https://your-project-repo/charts/k8s-mcp-server