# Default values for k8s-mcp-server chart

image:
  repository: ginnux/k8s-mcp-server
  pullPolicy: IfNotPresent
  tag: "latest"

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: k8s-mcp-server.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

podDisruptionBudget:
  enabled: false
  minAvailable: 1

networkPolicy:
  enabled: false

serviceAccount:
  create: true
  annotations: {}
  name: ""

clusterRole:
  create: true
  rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

env:
  SERVER_MODE: sse
  SERVER_PORT: 8080

useKubeconfigSecret: false
kubeconfigSecretName: k8s-mcp-kubeconfig

nodeSelector: {}
tolerations: []
affinity: {}