apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-proxy.configMapName" . }}
  labels:
    {{- include "mcp-proxy.labels" . | nindent 4 }}
data:
  servers-config.json: |
    {{- if .Values.config.servers }}
    {{- .Values.config.servers | toJson | nindent 4 }}
    {{- else }}
    {
      "servers": {
        "filesystem": {
          "command": "npx",
          "args": ["-y", "@modelcontextprotocol/server-filesystem", "/tmp"],
          "env": {},
          "enabled": true,
          "executionContext": "remote"
        },
        "web-search": {
          "command": "npx",
          "args": ["-y", "@modelcontextprotocol/server-web-search"],
          "env": {},
          "enabled": true,
          "executionContext": "remote"
        },
        "python-example": {
          "command": "python3",
          "args": ["-c", "print('Python MCP server stub - would run actual Python MCP server here')"],
          "env": {},
          "enabled": true,
          "executionContext": "remote"
        },
        "go-example": {
          "command": "go",
          "args": ["version"],
          "env": {},
          "enabled": true,
          "executionContext": "remote"
        },
        "java-example": {
          "command": "java",
          "args": ["-version"],
          "env": {},
          "enabled": true,
          "executionContext": "remote"
        }
      }
    }
    {{- end }}